[package]
name = "kernel"
version = "0.1.0"
authors = ["garasubo <garasubo@gmail.com>"]
edition = "2018"

[dependencies]
arch = { path = "../arch" }
device = { path = "../device" }
util = { path = "../util" }
rt = { path = "../rt" }
embedded-hal = "0.2.2"